on:
  push:
    branches: [ main ]

name: storageaccount

jobs:

  Backend_storage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
        ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}  
       ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}  
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}  
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        
    - name: Prepare artifact
      shell: bash
      run: |
        az group create --name skywave-prod --location eastus2
        az storage account create --resource-group skywave-prod --name skywaveprodtfstate --location eastus2 --sku Standard_LRS --kind StorageV2
        az storage container create -n skywavestate --public-access blob --account-name skywaveprodtfstate
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
