on:
  push:
    branches: [ main ]

name: storageaccount

jobs:

  Backend_storage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure login
      id: login
      uses: azure/login@v1.4.3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Prepare artifact
      shell: bash
      run: |
        az group create --name skywave-prod --location eastasia
        az storage account create --resource-group skywave-prod --name skywaveprodtfstate01 --location eastasia --sku Standard_LRS --kind StorageV2
        az storage container create -n skywavestate --public-access blob --account-name skywaveprodtfstate01
        
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
